title: SimpleCode
production_url : http://www.simplecode.me

author: Alex Jackson
twitter: alexjohnj
github: alexjohnj

paginate: 5
permalink:   /:year/:month/:day/:title/
safe:        false
port: 4000
baseurl:    /

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    true
markdown:    rdiscount
