title: SimpleCode
production_url : http://alexjohnj.github.com/simplecode/

author: Alex Jackson
twitter: alexjohnj
github: alexjohnj

# permalink:   /:year/:month/:day/:title/
# New Stuff

source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     []
keep_files:  ['.git','.svn']
gems:        []
timezone:    nil
encoding:    nil

future:      true
show_drafts: false
limit_posts: 0
highlighter: pygments

relative_permalinks: true

permalink:     date
paginate_path: 'page:num'
paginate:      5

markdown:      rdiscount
markdown_ext:  markdown,mkdown,mkdn,mkd,md
textile_ext:   textile

excerpt_separator: "\n\n"

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     "/simplecode"
lsi:         false

rdiscount:
  extensions: []
